### ISSUE TITLE
Implement Dynamic Field Mapping in azure-ai-search Package in azure-db

### ISSUE THREAD

**Issue by k-allagbe** [ai-cfia/azure-db#7]
In the `azure-ai-search` package, the current field mapping between Azure AI Search index results and the frontend data is hardcoded. This inflexibility poses challenges in adapting to changes in the index structure without altering the code.

## Tasks:
- [ ] Analyze the existing hardcoded field mapping setup.
- [ ] Design and implement a dynamic field mapping system.
- [ ] Ensure the new system accommodates index structure changes seamlessly.
- [ ] Write tests to validate the functionality and stability of the new mapping system.

## Acceptance Criteria:
- Field mappings between the Azure AI Search index and the frontend adjust dynamically to changes in the index structure without requiring code modifications.
- The new implementation accurately represents data on the frontend.
- The solution passes all tests, confirming its stability and effectiveness.

**Comment by rngadam** [comment]
@k-allagbe please report on which off the shelf library you've evaluated to do nested to nested object mapping.

Is it possible, for example, to achieve the same result with pydantic?

https://stackoverflow.com/questions/71574543/how-to-transform-data-for-pydantic-models

**Comment by k-allagbe** [comment]
> @k-allagbe please report on which off the shelf library you've evaluated to do nested to nested object mapping.
> 
> Is it possible, for example, to achieve the same result with pydantic?
> 
> https://stackoverflow.com/questions/71574543/how-to-transform-data-for-pydantic-models

I've evaluated `dpath-python` and `pydantic`.

Pydantic would help with model design but doesn't seem to solve the dynamic aspect. Code would still need to be modified if the structure of the index query results change afaik. Maybe with a bit of ninjutsu it could work.

Dpath can handle this but felt at the time like cracking a nut with a sledghammer. But in retrospect, for performance and maintainability, it looks like the better way to go.
